[build]
  command = "npm run build"
  functions = "dist/netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# Pas de redirects nécessaires pour les fonctions Netlify
